import {
  Home,
  Atom,
  Sigma,
  Layers,
  Network,
  TrendingUp,
  Eye,
  FlaskConical,
  Code2,
  Brain,
  Sparkles,
  Cpu,
  BookOpen,
  Search,
  Settings,
  GraduationCap,
  Briefcase,
  Compass,
  FileText,
  Library,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export type NavItem = {
  title: string;
  href: string;
  icon: LucideIcon;
  description?: string;
  badge?: string;
  children?: NavItem[];
};

export const navigation: NavItem[] = [
  { title: 'Home', href: '/', icon: Home, description: 'The world of tensors' },
  {
    title: 'Tensor Basics',
    href: '/basics',
    icon: Atom,
    description: 'Foundations: tensor, mode, fiber, slice',
    children: [
      { title: 'Tensor', href: '/basics/tensor', icon: Atom },
      { title: 'Mode & Fibers', href: '/basics/mode-fiber', icon: Sigma },
      { title: 'Slices', href: '/basics/slices', icon: Layers },
      { title: 'Rank', href: '/basics/rank', icon: TrendingUp },
      { title: 'Norms & Inner Product', href: '/basics/norm', icon: Sigma },
      { title: 'Outer Product', href: '/basics/outer-product', icon: Sigma },
      { title: 'Kronecker Product', href: '/basics/kronecker', icon: Sigma },
      { title: 'Khatri-Rao Product', href: '/basics/khatri-rao', icon: Sigma },
      { title: 'Hadamard Product', href: '/basics/hadamard', icon: Sigma },
      { title: 'Einstein Summation', href: '/basics/einsum', icon: Sigma },
      { title: 'Matricization', href: '/basics/matricization', icon: Layers },
      { title: 'Tensorization', href: '/basics/tensorization', icon: Layers },
    ],
  },
  {
    title: 'Tensor Algebra',
    href: '/algebra',
    icon: Sigma,
    description: 'Products, contractions, reshaping',
  },
  {
    title: 'Tensor Decompositions',
    href: '/decompositions',
    icon: Layers,
    description: 'The core of this platform',
    badge: 'Core',
    children: [
      { title: 'CP / CANDECOMP / PARAFAC', href: '/decompositions/cp', icon: Layers, badge: 'Core' },
      { title: 'Tucker & HOSVD', href: '/decompositions/tucker', icon: Layers, badge: 'Core' },
      { title: 'HOOI', href: '/decompositions/hooi', icon: Layers },
      { title: 'Tensor Train (TT)', href: '/decompositions/tt', icon: Layers, badge: 'Core' },
      { title: 'Matrix Product State', href: '/decompositions/mps', icon: Layers },
      { title: 'Hierarchical Tucker', href: '/decompositions/ht', icon: Layers },
      { title: 'Tensor Ring (TR)', href: '/decompositions/tr', icon: Layers, badge: 'Core' },
      { title: 'Tree Tensor Network', href: '/decompositions/ttn', icon: Layers },
      { title: 'PEPS', href: '/decompositions/peps', icon: Layers },
      { title: 'MERA', href: '/decompositions/mera', icon: Layers },
      { title: 'Block Term Decomposition', href: '/decompositions/btd', icon: Layers },
      { title: 't-SVD', href: '/decompositions/t-svd', icon: Layers },
      { title: 'Tensor CUR / Sketch', href: '/decompositions/cur', icon: Layers },
      { title: 'PARATUCK / INDSCAL', href: '/decompositions/paratuck', icon: Layers },
      { title: 'DEDICOM', href: '/decompositions/dedicom', icon: Layers },
      { title: 'Bayesian CP / Tucker', href: '/decompositions/bayesian', icon: Layers },
      { title: 'Sparse / Nonnegative', href: '/decompositions/sparse', icon: Layers },
      { title: 'Robust Tensor PCA', href: '/decompositions/rtpca', icon: Layers },
      { title: 'Tensor Completion', href: '/decompositions/completion', icon: Layers, badge: 'Hot' },
      { title: 'Streaming & Online', href: '/decompositions/streaming', icon: Layers },
      { title: 'All Decompositions', href: '/decompositions', icon: Library },
    ],
  },
  {
    title: 'Tensor Networks',
    href: '/networks',
    icon: Network,
    description: 'TT, MPS, PEPS, MERA, DMRG, TEBD',
    children: [
      { title: 'Overview', href: '/networks', icon: Network },
      { title: 'DMRG', href: '/networks/dmrg', icon: Network },
      { title: 'TEBD', href: '/networks/tebd', icon: Network },
      { title: 'Canonical Form', href: '/networks/canonical', icon: Network },
      { title: 'Born Machine', href: '/networks/born', icon: Network },
      { title: 'Riemannian Optimization', href: '/networks/riemannian', icon: Network },
    ],
  },
  {
    title: 'Optimization',
    href: '/optimization',
    icon: TrendingUp,
    description: 'ALS, GD, SGD, Adam, HALS, Riemannian',
    children: [
      { title: 'Alternating Least Squares', href: '/optimization/als', icon: TrendingUp },
      { title: 'Gradient Descent', href: '/optimization/gd', icon: TrendingUp },
      { title: 'Adam & SGD', href: '/optimization/adam', icon: TrendingUp },
      { title: 'HALS', href: '/optimization/hals', icon: TrendingUp },
      { title: 'Riemannian', href: '/optimization/riemannian', icon: TrendingUp },
    ],
  },
  {
    title: 'Visualization',
    href: '/visualization',
    icon: Eye,
    description: 'Interactive 3D tensor playground',
    children: [
      { title: 'Tensor Viewer', href: '/visualization/viewer', icon: Eye },
      { title: 'CP Animation', href: '/visualization/cp', icon: Eye },
      { title: 'Tucker Animation', href: '/visualization/tucker', icon: Eye },
      { title: 'TT Animation', href: '/visualization/tt', icon: Eye },
      { title: 'MPS / MERA', href: '/visualization/mps', icon: Eye },
      { title: 'Singular Values', href: '/visualization/svd', icon: Eye },
    ],
  },
  {
    title: 'Interactive Playground',
    href: '/playground',
    icon: FlaskConical,
    description: 'Run real decompositions in your browser',
    badge: 'Live',
  },
  {
    title: 'Code Center',
    href: '/code',
    icon: Code2,
    description: 'Python, MATLAB, NumPy, PyTorch, JAX',
    children: [
      { title: 'Python (NumPy)', href: '/code/python', icon: Code2 },
      { title: 'Python (TensorLy)', href: '/code/tensorly', icon: Code2 },
      { title: 'Python (PyTorch)', href: '/code/pytorch', icon: Code2 },
      { title: 'Python (JAX)', href: '/code/jax', icon: Code2 },
      { title: 'MATLAB (Tensor Toolbox)', href: '/code/matlab', icon: Code2 },
    ],
  },
  {
    title: 'AI Applications',
    href: '/ai',
    icon: Brain,
    description: 'LLM, Transformer, MoE, LoRA, Diffusion',
    badge: 'New',
    children: [
      { title: 'Overview', href: '/ai', icon: Brain },
      { title: 'Large Language Models', href: '/ai/llm', icon: Brain },
      { title: 'Transformer Compression', href: '/ai/transformer', icon: Brain },
      { title: 'LoRA & PEFT', href: '/ai/lora', icon: Brain },
      { title: 'Mixture of Experts', href: '/ai/moe', icon: Brain },
      { title: 'Diffusion Models', href: '/ai/diffusion', icon: Brain },
      { title: 'Recommender Systems', href: '/ai/recsys', icon: Brain },
      { title: 'GNN', href: '/ai/gnn', icon: Brain },
    ],
  },
  {
    title: 'Quantum Information',
    href: '/quantum',
    icon: Cpu,
    description: 'Quantum states, circuits, DMRG, VQE',
    children: [
      { title: 'Overview', href: '/quantum', icon: Cpu },
      { title: 'Quantum States', href: '/quantum/states', icon: Cpu },
      { title: 'Quantum Circuits', href: '/quantum/circuits', icon: Cpu },
      { title: 'Density Matrix', href: '/quantum/density', icon: Cpu },
      { title: 'Entanglement', href: '/quantum/entanglement', icon: Cpu },
      { title: 'VQE', href: '/quantum/vqe', icon: Cpu },
      { title: 'QAOA', href: '/quantum/qaoa', icon: Cpu },
    ],
  },
  {
    title: 'Applications',
    href: '/applications',
    icon: Briefcase,
    description: 'Image, EEG, MRI, video, signal',
    children: [
      { title: 'Overview', href: '/applications', icon: Briefcase },
      { title: 'Image Compression', href: '/applications/image', icon: Briefcase },
      { title: 'EEG / fMRI', href: '/applications/eeg', icon: Briefcase },
      { title: 'Recommender', href: '/applications/recsys', icon: Briefcase },
      { title: 'Video Analytics', href: '/applications/video', icon: Briefcase },
      { title: 'Remote Sensing', href: '/applications/remote-sensing', icon: Briefcase },
    ],
  },
  {
    title: 'Exercises',
    href: '/exercises',
    icon: GraduationCap,
    description: 'Quizzes and problem sets',
  },
  {
    title: 'Resources',
    href: '/resources',
    icon: BookOpen,
    description: 'Books, papers, lectures',
  },
  {
    title: 'Latest Papers',
    href: '/papers',
    icon: FileText,
    description: 'arXiv weekly digest',
    badge: 'Hot',
  },
  { title: 'Search', href: '/search', icon: Search, description: 'Search everything' },
  { title: 'Settings', href: '/settings', icon: Settings, description: 'Preferences' },
];

export const learningPath = [
  { level: 'Beginner', href: '/path/beginner', color: 'from-emerald-500 to-teal-500' },
  { level: 'Intermediate', href: '/path/intermediate', color: 'from-blue-500 to-indigo-500' },
  { level: 'Advanced', href: '/path/advanced', color: 'from-violet-500 to-purple-500' },
  { level: 'Research', href: '/path/research', color: 'from-rose-500 to-pink-500' },
];
